export const arte = [
    {domanda: 'Chi dipinse il famoso quadro "La Gioconda"?', risposta: 'Leonardo da Vinci'},
    {domanda: 'Qual è l\'arte di creare sculture intagliando il legno?', risposta: 'Scultura lignea'},
    {domanda: 'Qual è il movimento artistico noto per le sue opere geometriche e astratte, spesso caratterizzate da colori primari?', risposta: 'De Stijl'},
    {domanda: 'Chi è l\'autore dell\'opera "Notte stellata" che rappresenta un cielo notturno con stelle a spirale?', risposta: 'Vincent van Gogh'},
    {domanda: 'Qual è il periodo storico noto per la sua enfasi sulla bellezza ideale e l\'equilibrio nelle arti, ispirato dai modelli dell\'antica Grecia e Roma?', risposta: 'Rinascimento'},
    {domanda: 'Chi è l\'artista concettuale noto per il suo lavoro "Fontana", una fontana comune trasformata in arte?', risposta: 'Marcel Duchamp'},
    {domanda: 'Qual è il materiale tradizionalmente utilizzato per scolpire le statue nel giapponese "netsuke"?', risposta: 'Avorio'},
    {domanda: 'Qual è l\'opera d\'arte più famosa di Michelangelo, situata nella Cappella Sistina?', risposta: 'La Creazione di Adamo'},
    {domanda: 'Qual è il movimento artistico noto per le sue opere surreali e oniriche, spesso con orologi molli, creato da Salvador Dalí?', risposta: 'Surrealismo'},
    {domanda: 'Chi è l\'artista pop noto per le sue opere con lattine di zuppa Campbell e banane, tra cui "Campbell\'s Soup Cans"?', risposta: 'Andy Warhol'},
    {domanda: 'Chi è l\'autore del dipinto "La Gioconda"?', risposta: 'Leonardo da Vinci'},
{domanda: 'Qual è il nome dell\'arte di piegare il carta per creare figure?', risposta: 'Origami'},
{domanda: 'Chi è considerato il padre della scultura rinascimentale?', risposta: 'Donatello'},
{domanda: 'In quale paese è nato il movimento artistico chiamato "Impressionismo"?', risposta: 'Francia'},
{domanda: 'Qual è il nome dell\'arte di disegnare o scrivere con bei caratteri?', risposta: 'Calligrafia'},
{domanda: 'Chi è l\'autore del dipinto "Notte stellata"?', risposta: 'Vincent van Gogh'},
{domanda: 'Qual è il nome dell\'arte di intagliare o scolpire la forma di un oggetto da un blocco di materiale?', risposta: 'Scultura'},
{domanda: 'In quale movimento artistico è famoso il dipinto "La persistenza della memoria" di Salvador Dalí?', risposta: 'Surrealismo'},
{domanda: 'Chi è l\'autore della scultura "Il David"?', risposta: 'Michelangelo'},
{domanda: 'Qual è il nome dell\'arte di creare immagini con piccoli pezzi di vetro o tessere?', risposta: 'Mosaico'},
{domanda: 'Chi è l\'autore della famosa opera lirica "La Traviata"?', risposta: 'Giuseppe Verdi'},
{domanda: 'Qual è il nome dell\'arte di modellare la forma di un oggetto da un materiale come argilla?', risposta: 'Scultura in terracotta'},
{domanda: 'Chi è l\'autore del quadro "La nascita di Venere"?', risposta: 'Sandro Botticelli'},
{domanda: 'Qual è il nome dell\'arte di decorare oggetti con pezzi di vetro colorato?', risposta: 'Vetrate artistiche'},
{domanda: 'Chi è l\'autore del dipinto "Le tre età dell\'uomo"?', risposta: 'Gustav Klimt'},
{domanda: 'Chi è l\'autore della statua di David a Firenze?', risposta: 'Michelangelo'},
{domanda: 'Qual è il nome dell\'arte di creare immagini da piccoli pezzi di carta colorata?', risposta: 'Collage'},
{domanda: 'In quale movimento artistico è noto il dipinto "La Notte Stellata" di Vincent van Gogh?', risposta: 'Post-Impressionismo'},
{domanda: 'Chi è l\'autore della famosa opera lirica "Carmen"?', risposta: 'Georges Bizet'},
{domanda: 'In quale movimento artistico è noto il dipinto "Guernica" di Pablo Picasso?', risposta: 'Cubismo'},
{domanda: 'Chi è l\'autore del quadro "La nascita di Venere"?', risposta: 'Sandro Botticelli'},
{domanda: 'In quale movimento artistico è noto il dipinto "l\'urlo" di Edvard Munch?', risposta: 'Simbolismo'},
{domanda: 'Chi è l\'autore del dipinto "Le tre età dell\'uomo"?', risposta: 'Gustav Klimt'},
{domanda: 'Qual è il nome dell\'arte di intagliare la forma di un oggetto da un legno?', risposta: 'Scultura in legno'},
{domanda: 'In quale movimento artistico è noto il dipinto "La Persistenza della Memoria" di Salvador Dalí?', risposta: 'Surrealismo'},
{domanda: 'Chi è l\'autore della statua di David a Firenze?', risposta: 'Michelangelo'},
{domanda: 'Qual è il nome dell\'arte di creare immagini da piccoli pezzi di carta colorata?', risposta: 'Collage'},
{domanda: 'In quale movimento artistico è noto il dipinto "Natura morta con ombrelli" di Rene Magritte?', risposta: 'Surrealismo'},
{domanda: 'Chi è l\'autore del dipinto "l\'ultima Cena"?', risposta: 'Leonardo da Vinci'},
{domanda: 'Qual è il nome dell\'arte di creare immagini con piccoli pezzi di vetro colorato?', risposta: 'Vetrate artistiche'},
{domanda: 'In quale movimento artistico è noto il dipinto "Il Bacio" di Gustav Klimt?', risposta: 'Simbolismo'},
{domanda: 'Chi è l\'autore del quadro "La ragazza con l\'orecchino di perla"?', risposta: 'Johannes Vermeer'},
{domanda: 'Qual è il nome dell\'arte di creare sculture usando materiali di recupero?', risposta: 'Arte del riciclo'},
{domanda: 'Chi è l\'autore del dipinto "La persistenza della memoria"?', risposta: 'Salvador Dalí'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte con piccoli pezzi di vetro o pietra?', risposta: 'Mosaico'},
{domanda: 'In quale movimento artistico è noto il dipinto "Donna con un ombrello" di Pierre-Auguste Renoir?', risposta: 'Impressionismo'},
{domanda: 'Chi è l\'autore del dipinto "Il Naufragio della Medusa"?', risposta: 'Théodore Géricault'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte usando il fango o l\'argilla cotta?', risposta: 'Ceramica'},
{domanda: 'In quale movimento artistico è noto il dipinto "La camera da letto ad Arles" di Vincent van Gogh?', risposta: 'Post-Impressionismo'},
{domanda: 'Chi è l\'autore della scultura "Il Pensatore"?', risposta: 'Auguste Rodin'},
{domanda: 'Qual è il nome dell\'arte di ritagliare figure da carta nera?', risposta: 'Silhouette'},
{domanda: 'In quale movimento artistico è noto il dipinto "Le tre Grazie" di Raffaello?', risposta: 'Rinascimento'},
{domanda: 'Chi è l\'autore del dipinto "Il bacio"?', risposta: 'Gustav Klimt'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte utilizzando fili colorati?', risposta: 'Arte tessile'},
{domanda: 'In quale movimento artistico è noto il dipinto "Notte stellata sul Rodano" di Vincent van Gogh?', risposta: 'Post-Impressionismo'},
{domanda: 'Chi è l\'autore del dipinto "La scuola di Atene"?', risposta: 'Raffaello Sanzio'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte con piccoli pezzi di vetro colorato e piombo?', risposta: 'Vetrate artistiche'},
{domanda: 'In quale movimento artistico è noto il dipinto "La nascita di Venere" di Sandro Botticelli?', risposta: 'Rinascimento'},
{domanda: 'Chi è l\'autore del dipinto "l\'urlo"?', risposta: 'Edvard Munch'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte usando sottili strisce di carta intrecciata?', risposta: 'Quilling'},
{domanda: 'In quale movimento artistico è noto il dipinto "La Sposa di Klimt" di Egon Schiele?', risposta: 'Espressionismo'},
{domanda: 'Chi è l\'autore del dipinto "La nascita di Venere"?', risposta: 'Sandro Botticelli'},
{domanda: 'Qual è il nome dell\'arte di creare opere d\'arte con piccoli pezzi di tessuto cuciti insieme?', risposta: 'Quilting'}.
]