export const cinema = [
    {domanda: 'Qual è il film che ha vinto l\'Oscar come Miglior Film nel 1994 e presenta personaggi come Forrest Gump e Jenny Curran?', risposta: 'Forrest Gump'},
    {domanda: 'Chi ha diretto il film "Il Padrino"?', risposta: 'Francis Ford Coppola'},
    {domanda: 'In quale film del 1985 un giovane Michael J. Fox interpreta un adolescente viaggiatore nel tempo?', risposta: 'Ritorno al futuro'},
    {domanda: 'Chi è stato l\'attore che ha interpretato il personaggio di James Bond nel film "Skyfall" del 2012?', risposta: 'Daniel Craig'},
    {domanda: 'Qual è il nome del regista di "Pulp Fiction" e "Kill Bill"?', risposta: 'Quentin Tarantino'},
    {domanda: 'In quale film del 1977 il personaggio Luke Skywalker affronta Darth Vader per la prima volta?', risposta: 'Guerre stellari (Star Wars: Episode IV - A New Hope)'},
    {domanda: 'Qual è il nome del robot animato protagonista del film d\'animazione Pixar del 2008?', risposta: 'Wall-E'},
    {domanda: 'Qual è il film del 1990 diretto da Martin Scorsese e interpretato da Robert De Niro come un gangster?', risposta: 'Quei bravi ragazzi (Goodfellas)'},
    {domanda: 'In quale film del 1993 Steven Spielberg porta i dinosauri sulla terra grazie alla tecnologia CGI?', risposta: 'Jurassic Park'},
    {domanda: 'Chi è stato l\'attore protagonista del film "Il Gladiatore" del 2000, diretto da Ridley Scott?', risposta: 'Russell Crowe'},
    {domanda: 'Qual è il titolo del film del 2008 diretto da Christopher Nolan, noto per la sua trama intricata sul viaggio nel tempo?', risposta: 'Inception'},
    {domanda: 'Chi ha vinto l\'Oscar come Miglior Attore per il suo ruolo in "The Revenant" del 2015?', risposta: 'Leonardo DiCaprio'},
    {domanda: 'Quale regista è noto per il suo lavoro su "The Dark Knight Trilogy" e "Inception"?', risposta: 'Christopher Nolan'},
    {domanda: 'Qual è il film del 2003 basato su una storia vera che segue la vita di un giovane indiano chiamato Jamal Malik?', risposta: 'Slumdog Millionaire'},
    {domanda: 'Qual è il film del 2010 diretto da David Fincher, basato su un romanzo di Mark Zuckerberg e la creazione di Facebook?', risposta: 'The Social Network'},
    {domanda: 'Chi ha diretto il film d\'animazione "Frozen" del 2013?', risposta: 'Chris Buck e Jennifer Lee'},
    {domanda: 'Qual è il titolo del film del 2019 che ha vinto l\'Oscar come Miglior Film Straniero e Miglior Regista per Bong Joon-ho?', risposta: 'Parasite'},
    {domanda: 'In quale film del 2014 Matthew McConaughey interpreta un astronauta alla ricerca di un nuovo pianeta per l\'umanità?', risposta: 'Interstellar'},
    {domanda: 'Qual è il film del 2017 diretto da Jordan Peele, noto per il suo commento sociale e l\'horror psicologico?', risposta: 'Get Out'},
    {domanda: 'Chi ha interpretato il personaggio di Iron Man/Tony Stark nell\'Universo Cinematografico Marvel?', risposta: 'Robert Downey Jr.'},
    {domanda: 'Qual è stato il primo film del Marvel Cinematic Universe (MCU)?', risposta: 'Iron Man (2008)'},
{domanda: 'Chi ha diretto il film "Inception" del 2010?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è stato il film vincitore dell\'Oscar come Miglior Film nel 2020?', risposta: 'Parasite'},
{domanda: 'Qual è stato il titolo del primo film della serie "Harry Potter"?', risposta: 'Harry Potter e la pietra filosofale'},
{domanda: 'Chi ha interpretato il protagonista nel film "The Revenant" del 2015?', risposta: 'Leonardo DiCaprio'},
{domanda: 'Quale film ha introdotto il personaggio di Deadpool nell\'universo cinematografico Marvel?', risposta: 'Deadpool (2016)'},
{domanda: 'Chi ha diretto il film d\'animazione "Toy Story 3"?', risposta: 'Lee Unkrich'},
{domanda: 'Qual è il nome del regista di "La La Land" del 2016?', risposta: 'Damien Chazelle'},
{domanda: 'In quale film del 2003 Quentin Tarantino ha diretto due segmenti distinti?', risposta: 'Kill Bill: Volume 1'},
{domanda: 'Chi ha interpretato il personaggio di Katniss Everdeen nella serie "Hunger Games"?', risposta: 'Jennifer Lawrence'},
{domanda: 'Qual è stato il primo film della saga "Fast & Furious"?', risposta: 'The Fast and the Furious (2001)'},
{domanda: 'Chi ha interpretato il Joker nel film "The Dark Knight" del 2008?', risposta: 'Heath Ledger'},
{domanda: 'Chi ha interpretato il personaggio di Tony Stark/Iron Man?', risposta: 'Robert Downey Jr.'},
{domanda: 'Quale film del 2010 ha ispirato il meme "Inception Horn"?', risposta: 'Inception'},
{domanda: 'Chi ha diretto il film "La forma dell\'acqua" del 2017?', risposta: 'Guillermo del Toro'},
{domanda: 'Qual è stato il primo film della saga "Pirati dei Caraibi"?', risposta: 'La maledizione della prima luna (2003)'},
{domanda: 'Quale film ha vinto l\'Oscar come Miglior Film d\'Animazione nel 2019?', risposta: 'Spider-Man: Un nuovo universo'},
{domanda: 'Chi ha diretto il film "Mad Max: Fury Road" del 2015?', risposta: 'George Miller'},
{domanda: 'Chi ha diretto il film "Black Swan" del 2010?', risposta: 'Darren Aronofsky'},
{domanda: 'Qual è stato il titolo del film del 2006 che ha portato alla fama il personaggio di Borat?', risposta: 'Borat - Studio culturale sull\'America a beneficio della gloriosa nazione del Kazakistan'},
{domanda: 'Quale film del 2017 ha vinto l\'Oscar come Miglior Film?', risposta: 'Moonlight'},
{domanda: 'Chi ha diretto il film "La La Land" del 2016?', risposta: 'Damien Chazelle'},
{domanda: 'Qual è stato il titolo del film del 2012 basato su un libro di Suzanne Collins?', risposta: 'Hunger Games: Il canto della rivolta - Parte 1'},
{domanda: 'Chi ha interpretato il personaggio di Neo nella trilogia "Matrix"?', risposta: 'Keanu Reeves'},
{domanda: 'Quale film del 2014 ha vinto l\'Oscar come Miglior Film?', risposta: '12 anni schiavo'},
{domanda: 'Chi ha diretto il film "Il discorso del re" del 2010?', risposta: 'Tom Hooper'},
{domanda: 'Qual è stato il titolo del film del 2018 che ha portato alla fama il personaggio di Black Panther?', risposta: 'Black Panther'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2000?', risposta: 'Il gladiatore'},
{domanda: 'Chi ha diretto il film "The Dark Knight" del 2008?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il titolo del primo film della saga di Harry Potter, uscito nel 2001?', risposta: 'Harry Potter e la Pietra Filosofale'},
{domanda: 'Qual è il nome dell\'attore che interpreta Iron Man nella serie di film Marvel?', risposta: 'Robert Downey Jr.'},
{domanda: 'Qual è il titolo del film Disney del 2003 che racconta la storia di una famiglia di pesci?', risposta: 'Alla ricerca di Nemo'},
{domanda: 'Qual è il nome del terzo film della saga di "Il Signore degli Anelli" uscito nel 2003?', risposta: 'Il ritorno del re'},
{domanda: 'Chi ha diretto il film "La La Land" del 2016?', risposta: 'Damien Chazelle'},
{domanda: 'Qual è il titolo del film animato del 2013 in cui ci sono due regine di ghiaccio?', risposta: 'Frozen'},
{domanda: 'Chi ha diretto il film "Inception" del 2010?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Belle nel film "La Bella e la Bestia" del 2017?', risposta: 'Emma Watson'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2001?', risposta: 'A Beautiful Mind'},
{domanda: 'Qual è il titolo del film del 2015 in cui Tom Hardy interpreta il personaggio di Mad Max?', risposta: 'Mad Max: Fury Road'},
{domanda: 'Chi ha diretto il film "The Social Network" del 2010?', risposta: 'David Fincher'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Katniss Everdeen nella serie di film "Hunger Games"?', risposta: 'Jennifer Lawrence'},
{domanda: 'Qual è il titolo del film del 2018 in cui Lady Gaga interpreta il ruolo principale?', risposta: 'A Star Is Born'},
{domanda: 'Chi ha diretto il film "Dunkirk" del 2017?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il nome dell\'attore che interpreta Jack Sparrow nella serie di film "Pirati dei Caraibi"?', risposta: 'Johnny Depp'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2018?', risposta: 'La forma dell\'acqua'},
{domanda: 'Qual è il titolo del film del 2009 in cui un uomo vive in un mondo pieno di robot?', risposta: 'District 9'},
{domanda: 'Chi ha diretto il film "Interstellar" del 2014?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il nome dell\'attore che interpreta Thor nella serie di film Marvel?', risposta: 'Chris Hemsworth'},
{domanda: 'Qual è il titolo del film animato del 2004 in cui i personaggi principali sono un leone e un pesce?', risposta: 'Il re leone 3D'},
{domanda: 'Chi ha diretto il film "Memento" del 2000?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Hermione nella serie di film di Harry Potter?', risposta: 'Emma Watson'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2016?', risposta: 'Moonlight'},
{domanda: 'Qual è il titolo del film del 2019 in cui Joaquin Phoenix interpreta il personaggio di Joker?', risposta: 'Joker'},
{domanda: 'Chi ha diretto il film "The Avengers" del 2012?', risposta: 'Joss Whedon'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Wonder Woman nella serie di film DC?', risposta: 'Gal Gadot'},
{domanda: 'Qual è il titolo del film animato del 2008 in cui i personaggi principali sono un robot e una formica?', risposta: 'Wall-E'},
{domanda: 'Chi ha diretto il film "Gravity" del 2013?', risposta: 'Alfonso Cuarón'},
{domanda: 'Qual è il nome dell\'attore che interpreta Black Panther nella serie di film Marvel?', risposta: 'Chadwick Boseman'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2010?', risposta: 'The Hurt Locker'},
{domanda: 'Qual è il titolo del film del 2014 in cui Matthew McConaughey interpreta un astronauta?', risposta: 'Interstellar'},
{domanda: 'Chi ha diretto il film "Black Swan" del 2010?', risposta: 'Darren Aronofsky'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Katniss Everdeen nella serie di film "Hunger Games"?', risposta: 'Jennifer Lawrence'},
{domanda: 'Qual è il titolo del film del 2012 in cui una giovane ragazza si ribella in una distopica versione del futuro?', risposta: 'Hunger Games'},
{domanda: 'Chi ha diretto il film "La La Land" del 2016?', risposta: 'Damien Chazelle'},
{domanda: 'Qual è il nome dell\'attore che interpreta Iron Man nella serie di film Marvel?', risposta: 'Robert Downey Jr.'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2017?', risposta: 'La La Land'},
{domanda: 'Qual è il titolo del film del 2019 in cui Joaquin Phoenix interpreta il personaggio di Joker?', risposta: 'Joker'},
{domanda: 'Chi ha diretto il film "Inception" del 2010?', risposta: 'Christopher Nolan'},
{domanda: 'Qual è il nome dell\'attore che interpreta Thor nella serie di film Marvel?', risposta: 'Chris Hemsworth'},
{domanda: 'Qual è il titolo del film del 2006 in cui i personaggi principali sono una cabina telefonica e un cattivo?', risposta: 'Babbel-Babbel'},
{domanda: 'Chi ha diretto il film "The Avengers" del 2012?', risposta: 'Joss Whedon'},
{domanda: 'Qual è il nome dell\'attrice che interpreta Wonder Woman nella serie di film DC?', risposta: 'Gal Gadot'},
{domanda: 'Qual è stato il film vincitore dell\'oscar come Miglior Film nel 2003?', risposta: 'Il signore degli anelli - Il ritorno del re'},
    ]