export const cultura = [
    {domanda: 'Qual è la capitale dell\'italia?', risposta: 'Roma'},
    {domanda: 'Qual è il fiume più lungo del mondo?', risposta: 'Il Nilo'},
    {domanda: 'In quale continente si trova il deserto del Sahara?', risposta: 'Africa'},
    {domanda: 'Qual è il metallo più leggero?', risposta: 'l\'alluminio'},
    {domanda: 'Qual è la montagna più alta del mondo?', risposta: 'L\'Everest'},
    {domanda: 'Quanti elementi chimici ha la tavola periodica?', risposta: '118'},
    {domanda: 'Qual è il più grande oceano del mondo?', risposta: 'Il Pacifico'},
    {domanda: 'Chi scrisse l\'opera "La Divina Commedia"?', risposta: 'Dante Alighieri'},
    {domanda: 'Qual è l\'autore delle opere "Romeo e Giulietta" e "Macbeth"?', risposta: 'William Shakespeare'},
    {domanda: 'In quale continente si trova l\'india?', risposta: 'Asia'},
    {domanda: 'Quale è la lingua più parlata al mondo?', risposta: 'Il cinese mandarino'},
    {domanda: 'Quale è il più grande deserto del mondo?', risposta: 'Il deserto dell\'antartide'},
    {domanda: 'Qual è il piatto tipico italiano a base di pasta, uova, guanciale e pecorino?', risposta: 'La carbonara'},
    {domanda: 'Quando è iniziata la seconda guerra mondiale?', risposta: 'Nel 1939'},
    {domanda: 'Qual è il simbolo chimico dell\'oro?', risposta: 'Au'},
    {domanda: 'Qual è il più grande mammifero terrestre?', risposta: 'L\'elefante'},
    {domanda: 'Qual è il simbolo chimico dell\'ossigeno?', risposta: 'O'},
    {domanda: 'Quale è il pianeta più vicino al Sole?', risposta: 'Mercurio'},
    {domanda: 'Qual è il libro più venduto al mondo?', risposta: 'La Bibbia'},
    {domanda: 'In quale anno è avvenuta la caduta del muro di Berlino?', risposta: '1989'},
    {domanda: 'Qual è il simbolo chimico del ferro?', risposta: 'Fe'},
    {domanda: 'Chi ha scritto "Orgoglio e Pregiudizio"?', risposta: 'Jane Austen'},
    {domanda: 'In quale paese si trova la torre Eiffel?', risposta: 'Francia'},
    {domanda: 'Qual è il più grande mammifero marino?', risposta: 'La balenottera blu'},
    {domanda: 'Qual è il simbolo chimico del carbonio?', risposta: 'C'},
    {domanda: 'Chi ha dipinto "La Gioconda"?', risposta: 'Leonardo da Vinci'},
    {domanda: 'Qual è il simbolo chimico del sodio?', risposta: 'Na'},
    {domanda: 'In quale paese si trova la Grande Muraglia?', risposta: 'Cina'},
    {domanda: 'Qual è il più grande stato degli Stati Uniti d\'America?', risposta: 'Alaska'},
    {domanda: 'Chi ha scritto "Guerra e Pace"?', risposta: 'Lev Tolstoj'},
    {domanda: 'Qual è il simbolo chimico del calcio?', risposta: 'Ca'},
    {domanda: 'Quale è il colore primario?', risposta: 'Il rosso'},
    {domanda: 'Qual è il periodo storico conosciuto come Rinascimento?', risposta: 'XIV-XVII secolo'},
    {domanda: 'Qual è la danza tipica della Spagna?', risposta: 'Il flamenco'},
    {domanda: 'In quale città si trova la statua della Libertà?', risposta: 'A New York'},
    {domanda: 'Qual è il simbolo chimico del piombo?', risposta: 'Pb'},
    {domanda: 'Chi ha scritto "1984"?', risposta: 'George Orwell'},
    {domanda: 'Qual è la città più popolosa del mondo?', risposta: 'Tokyo'},
    {domanda: 'Qual è il primo elemento nella tavola periodica?', risposta: 'l\'idrogeno'},
    {domanda: 'Qual è il simbolo chimico del nichel?', risposta: 'Ni'},
    {domanda: 'Chi ha scritto "Don Chisciotte"?', risposta: 'Miguel de Cervantes'},
    {domanda: 'In quale continente si trova il Brasile?', risposta: 'Sud America'},
    {domanda: 'Quante corde ha una chitarra classica?', risposta: '6'},
{domanda: 'Quale è il primo elemento nella tavola periodica?', risposta: 'Idrogeno'},
{domanda: 'Chi ha scritto "Romeo e Giulietta"?', risposta: 'William Shakespeare'},
{domanda: 'Qual è il fiume più lungo del mondo?', risposta: 'Il Nilo'},
{domanda: 'In quale continente si trova il deserto del Sahara?', risposta: 'Africa'},
{domanda: 'Quale è il metallo più leggero?', risposta: 'Lithium'},
{domanda: 'Quante costole ha il corpo umano?', risposta: '24'},
{domanda: 'Chi ha inventato il telefono?', risposta: 'Alexander Graham Bell'},
{domanda: 'Qual è la lingua più parlata al mondo?', risposta: 'Cinese mandarino'},
{domanda: 'In quale città si trova la Torre Eiffel?', risposta: 'Parigi'},
{domanda: 'Chi ha scritto "1984"?', risposta: 'George Orwell'},
{domanda: 'Quale oceano è più grande?', risposta: 'Oceano Pacifico'},
{domanda: 'Chi ha scritto "Orgoglio e pregiudizio"?', risposta: 'Jane Austen'},
{domanda: 'Quante zampe ha un ragno?', risposta: '8'},
{domanda: 'Qual è la montagna più alta del mondo?', risposta: 'Monte Everest'},
{domanda: 'Chi ha dipinto "La notte stellata"?', risposta: 'Vincent van Gogh'},
{domanda: 'Quale è il più grande paese del mondo?', risposta: 'Russia'},
{domanda: 'Qual è l\'animale più veloce del mondo?', risposta: 'Ghepardo'},
{domanda: 'Chi ha scritto "Il signore degli anelli"?', risposta: 'J.R.R. Tolkien'},
{domanda: 'Quale è il navigatore più utilizzato?', risposta: 'Google Maps'},
{domanda: 'Qual è la nota più alta nella scala musicale?', risposta: 'Do'},
{domanda: 'Chi è l\'artista di "Thriller"?', risposta: 'Michael Jackson'},
{domanda: 'Quante parti ha il cervello umano?', risposta: '3'},
{domanda: 'Chi ha dipinto "La creazione di Adamo"?', risposta: 'Michelangelo'},
{domanda: 'Qual è il più grande oceano?', risposta: 'Oceano Pacifico'},
{domanda: 'Quale è l\'animale che simboleggia la pace?', risposta: 'Colomba'},
{domanda: 'Qual è la capitale del Canada?', risposta: 'Ottawa'},
{domanda: 'Chi ha scritto "Il vecchio e il mare"?', risposta: 'Ernest Hemingway'},
{domanda: 'Quale è il liquido più denso?', risposta: 'Mercurio'},
{domanda: 'In quali sport olimpici si usa un arco e delle frecce?', risposta: 'Tiro con l\'arco'},
{domanda: 'Quale è il pianeta più vicino al sole?', risposta: 'Mercurio'},
{domanda: 'Qual è la lingua ufficiale dell\'argentina?', risposta: 'Spagnolo'},
{domanda: 'Chi ha scritto "Il Gattopardo"?', risposta: 'Giuseppe Tomasi di Lampedusa'},
{domanda: 'Quanto dura una partita di calcio?', risposta: '90 minuti'},
{domanda: 'Quale è l\'invenzione attribuita a Thomas Edison?', risposta: 'Lampadina'},
{domanda: 'Chi ha dipinto la Cappella Sistina?', risposta: 'Michelangelo'},
{domanda: 'Qual è il processo biologico che converte cibo in energia?', risposta: 'Digestione'},
{domanda: 'Quale è il primo libro della Bibbia?', risposta: 'Genesi'},
{domanda: 'Chi ha scritto "Moby Dick"?', risposta: 'Herman Melville'},
{domanda: 'Quante patte ha un gatto?', risposta: '4'},
{domanda: 'Qual è il più grande oceano del mondo?', risposta: 'Oceano Pacifico'},
 {domanda: 'Chi è l\'autore del libro "1984"?', risposta: 'George Orwell'}, 
 {domanda: 'Qual è il più lungo fiume del mondo?', risposta: 'Nilo'}, 
 {domanda: 'Qual è la capitale del Canada?', risposta: 'Ottawa'}, 
 {domanda: 'Qual è la montagna più alta del mondo?', risposta: 'Monte Everest'}, 
 {domanda: 'Quale pianeta è conosciuto come il pianeta rosso?', risposta: 'Marte'},
  {domanda: 'Quale paese è famoso per la muraglia cinese?', risposta: 'Cina'}, 
  {domanda: 'Qual è il più grande deserto del mondo?', risposta: 'Deserto del Sahara'}, 
  {domanda: 'Qual è la moneta ufficiale del Giappone?', risposta: 'Yen'}, 
  {domanda: 'Chi scrisse la tragedia "Romeo e Giulietta"?', risposta: 'William Shakespeare'}, 
  {domanda: 'Dove si trova la città di Machu Picchu?', risposta: 'Perù'}, 
  {domanda: 'Qual è il fiume più lungo d\'Europa?', risposta: 'Volga'}, 
  {domanda: 'Qual è il più grande lago d\'America?', risposta: 'Lago Superiore'}, 
  {domanda: 'Qual è l\'attuale presidente degli Stati Uniti?', risposta: 'Joe Biden'}, 
  {domanda: 'Quale animale è il più veloce del mondo?', risposta: 'Ghepardo'}, 
  {domanda: 'Chi ha dipinto il quadro "La Gioconda"?', risposta: 'Leonardo da Vinci'}, 
  {domanda: 'Quale lingua si parla in Brasile?', risposta: 'Portoghese'}, 
  {domanda: 'Qual è l\'invenzione più famosa di Thomas Edison?', risposta: 'Lampadina'}, 
  {domanda: 'Quale città è conosciuta come la città eterna?', risposta: 'Roma'}, 
  {domanda: 'Quale strumento usano i chirurghi per controllare il battito cardiaco?', risposta: 'Elettrocardiografo'}, 
  {domanda: 'Quale paese ha vinto più medaglie d\'oro alle Olimpiadi?', risposta: 'Stati Uniti'}, 
  {domanda: 'Qual è il metallo più leggero?', risposta: 'Litio'}, 
  {domanda: 'Chi è l\'autore del quadro "l\'ultima cena"?', risposta: 'Leonardo da Vinci'}, 
  {domanda: 'Quale è la valuta ufficiale della Russia?', risposta: 'Rublo'}, 
  {domanda: 'Chi è l\'autore della teoria dell\'evoluzione?', risposta: 'Charles Darwin'}, 
  {domanda: 'Qual è il simbolo chimico dell\'oro?', risposta: 'Au'}, 
  {domanda: 'Quante ossa ha il corpo umano?', risposta: '206'}, 
  {domanda: 'Chi ha scritto il romanzo "Orgoglio e pregiudizio"?', risposta: 'Jane Austen'}, 
  {domanda: 'Quale è l\'unica lettera che non appare nel nome di nessuno degli Stati Uniti d\'America?', risposta: 'Q'}, 
  {domanda: 'In che paese si svolse la prima Olimpiade?', risposta: 'Grecia'}, 
  {domanda: 'Quale alimento simboleggia l\'italia?', risposta: 'Pizza'}, {domanda: 'Chi è l\'autore della scultura "David"?', risposta: 'Michelangelo'}, 
  {domanda: 'Quante corde ha una chitarra classica?', risposta: '6'}, 
  {domanda: 'Quale è il più grande stato degli Stati Uniti d\'America?', risposta: 'Alaska'}, 
  {domanda: 'Qual è la principale lingua ufficiale in India?', risposta: 'Hindi'}, 
  {domanda: 'Chi scrisse il romanzo "Il Gattopardo"?', risposta: 'Giuseppe Tomasi di Lampedusa'}, 
  {domanda: 'Quale è il più grande parco nazionale degli Stati Uniti?', risposta: 'Parco Nazionale di Wrangell-St. Elias'}, 
  {domanda: 'In che nazione si trova la torre di Pisa?', risposta: 'Italia'}, 
  {domanda: 'Quale paese confina con il Brasile?', risposta: 'Argentina'}, 
  {domanda: 'Quale è il paese più popoloso del mondo?', risposta: 'Cina'}, 
  {domanda: 'Chi ha scritto la famosa opera "Carmen"?', risposta: 'Georges Bizet'}, 
  {domanda: 'Quale è il nobile gas più abbondante nell\'atmosfera?', risposta: 'Azoto'}, 
  {domanda: 'Qual è il golfo più grande del mondo?', risposta: 'Golfo del Messico'}, 
  {domanda: 'In che anno fu compiuto lo sbarco sulla Luna?', risposta: '1969'}, 
  {domanda: 'Quale è l\'organo più grande del corpo umano?', risposta: 'Pelle'}, 
  {domanda: 'Chi è l\'autore del quadro "La notte stellata"?', risposta: 'Vincent van Gogh'},
  {domanda: 'Quale è il pianeta più grande del sistema solare?', risposta: 'Giove'},
{domanda: 'In quale anno è iniziata la prima guerra mondiale?', risposta: '1914'},
{domanda: 'Chi è l\'autore de "L\'isola del tesoro"?', risposta: 'Robert Louis Stevenson'},
{domanda: 'Quale animale è il simbolo del marchio Ferrari?', risposta: 'Cavallo'},
{domanda: 'Chi è l\'autore del dipinto "La Gioconda"?', risposta: 'Leonardo da Vinci'},
{domanda: 'Quanti continenti ci sono nel mondo?', risposta: '5'},
{domanda: 'Che cosa significa "OMG" nelle conversazioni online?', risposta: 'Oh my God'},
{domanda: 'Qual è la capitale dell\'Italia?', risposta: 'Roma'},
{domanda: 'In quale paese si trova la Torre Eiffel?', risposta: 'Francia'},
{domanda: 'Qual è il fiume più lungo del mondo?', risposta: 'Nilo'},
{domanda: 'Qual è il paese con la popolazione più numerosa del mondo?', risposta: 'Cina'},
{domanda: 'Chi è l\'autore del romanzo "1984"?', risposta: 'George Orwell'},
{domanda: 'Quale è il metallo più leggero?', risposta: 'Litio'},
{domanda: 'Quando è stata fondata Apple Inc.?', risposta: '1976'},
{domanda: 'Qual è il simbolo chimico dell\'oro?', risposta: 'Au'},
{domanda: 'Quale famoso scienziato fu l\'ideatore della teoria della relatività?', risposta: 'Albert Einstein'},
{domanda: 'Quale città è considerata la capitale del Regno Unito?', risposta: 'Londra'},
{domanda: 'Di quale paese è la città di Marrakech la capitale?', risposta: 'Marocco'},
{domanda: 'Qual è la montagna più alta del mondo?', risposta: 'Monte Everest'},
{domanda: "Qual è l'organo più grande del corpo umano?", risposta: 'Pelle'},
{domanda: 'Chi è l\'autore del romanzo "Il vecchio e il mare"?', risposta: 'Ernest Hemingway'},
{domanda: 'Quale animale è considerato il re della giungla?', risposta: 'Leone'},
{domanda: 'Chi è l\'autore del dipinto "La Notte Stellata"?', risposta: 'Vincent van Gogh'},
{domanda: 'Qual è l\'invenzione attribuita a Thomas Edison?', risposta: 'Lampadina'},
{domanda: 'Quale cantante ha realizzato l\'album "Thriller"?', risposta: 'Michael Jackson'},
{domanda: 'Quale scoperta fu fatta da Alexander Fleming?', risposta: 'Penicillina'},
{domanda: 'Quale famoso scrittore inglese ha scritto "Romeo e Giulietta"?', risposta: 'William Shakespeare'},
{domanda: 'In quale città si trova la Statua della Libertà?', risposta: 'New York'},
{domanda: 'Quale è la lingua più parlata al mondo?', risposta: 'Cinese mandarino'},
{domanda: 'Quale è lo stato più grande degli Stati Uniti?', risposta: 'Alaska'},
{domanda: 'Chi è l\'autore del romanzo "Il signore degli anelli"?', risposta: 'J.R.R. Tolkien'}
];