export const geografia = [
    {domanda: 'Qual è il continente più grande del mondo?', risposta: 'Asia'},
    {domanda: 'Qual è il fiume più lungo del mondo?', risposta: 'Nilo'},
    {domanda: 'In quale oceano si trova l\'isola di Pasqua?', risposta: 'Oceano Pacifico'},
    {domanda: 'Qual è il deserto più grande del mondo?', risposta: 'Sahara'},
    {domanda: 'Qual è la capitale del Canada?', risposta: 'Ottawa'},
    {domanda: 'Qual è la montagna più alta del mondo?', risposta: 'Monte Everest'},
    {domanda: 'In quale paese si trova la Torre Eiffel?', risposta: 'Francia'},
    {domanda: 'Qual è il lago più profondo del mondo?', risposta: 'Lago Baikal'},
    {domanda: 'In quale continente si trova ld\'egitto?', risposta: 'Africa'},
    {domanda: 'Quale è la capitale del Giappone?', risposta: 'Tokyo'},
    {domanda: 'Qual è il confine terrestre più lungo del mondo?', risposta: 'Confine tra Cina e Russia'},
    {domanda: 'Dove si trova il Colosseo?', risposta: 'Roma, Italia'},
    {domanda: 'Quale è la capitale del Brasile?', risposta: 'Brasilia'},
    {domanda: 'Qual è il mare più piccolo del mondo?', risposta: 'Mare di Azzorre'},
    {domanda: 'In quale paese si trova il Kilimangiaro?', risposta: 'Tanzania'},
    {domanda: 'Quale è la valle più famosa d\'Inghilterra?', risposta: 'Valle di Thames'},
    {domanda: 'In quale città si trova la Statua della Libertà?', risposta: 'New York'},
    {domanda: 'Qual è il paese meno popoloso del mondo?', risposta: 'Vaticano'},
    {domanda: 'Quale lago è condiviso da Canada e Stati Uniti?', risposta: 'Lago di Garda'},
    {domanda: 'In quale paese si trova Machu Picchu?', risposta: 'Perù'},
    {domanda: 'Quale è il fiume più largo dd\'europa?', risposta: 'Volga'},
    {domanda: 'Dove si trova il monumento di Stonehenge?', risposta: 'Inghilterra'},
    {domanda: 'Qual è il paese più grande dd\'europa?', risposta: 'Russia'},
    {domanda: 'Quale è la più grande cascata del mondo?', risposta: 'Cascate del Niagara'},
    {domanda: 'In quale oceano si trovano le Maldive?', risposta: 'Oceano Indiano'},
    {domanda: 'Qual è il fiume più lungo dd\'europa?', risposta: 'Volga'},
    {domanda: 'Dove si trova la Grande Muraglia Cinese?', risposta: 'Cina'},
    {domanda: 'Quale è la capitale del Marocco?', risposta: 'Rabat'},
    {domanda: 'Qual è la montagna più alta dd\'europa?', risposta: 'Monte Elbrus'},
    {domanda: 'Dove si trova il lago Titicaca?', risposta: 'Perù e Bolivia'},
    {domanda: 'Quale è la capitale dell\'australia?', risposta: 'Canberra'},
    {domanda: 'Qual è la barriera corallina più grande del mondo?', risposta: 'Grande Barriera Corallina, Australia'},
    {domanda: 'In quale oceano si trova l\'islanda?', risposta: 'Oceano Atlantico'},
    {domanda: 'Quale è la capitale della Spagna?', risposta: 'Madrid'},
    {domanda: 'Qual è il punto più basso della Terra?', risposta: 'Mar Morto'},
    {domanda: 'Quale è la città più popolosa d\'America?', risposta: 'Città del Messico'},
    {domanda: 'Quale nazione è chiamata la Terra del Sol Levante?', risposta: 'Giappone'},
    {domanda: 'In quale città si trova il famoso Teatro Greco?', risposta: 'Siracusa, Italia'},
    {domanda: 'Quale paese si estende su due continenti?', risposta: 'Turchia'},
    {domanda: 'Qual è il paese più piccolo del mondo?', risposta: 'Vaticano'},
    {domanda: 'Dove si trova il deserto di Atacama?', risposta: 'Cile'},
    {domanda: 'Qual è il fiume più lungo del mondo?', risposta: 'Il Nilo'},
    {domanda: 'Qual è la capitale del Canada?', risposta: 'Ottawa'},
    {domanda: 'Qual è il paese più grande del mondo in termini di superficie?', risposta: 'Russia'},
     {domanda: 'Qual è la montagna più alta del mondo?', risposta: 'Monte Everest'}, 
     {domanda: 'Qual è la capitale dell\'australia?', risposta: 'Canberra'},
      {domanda: 'In quale continente si trova il paese del Marocco?', risposta: 'Africa'},
       {domanda: 'Qual è la città più popolosa del mondo?', risposta: 'Tokyo'},
        {domanda: 'Qual è la capitale del Brasile?', risposta: 'Brasilia'},
         {domanda: 'In quale oceano si trova l\'isola di Tahiti?', risposta: 'Oceano Pacifico'},
          {domanda: 'Qual è il punto più basso della superficie terrestre?', risposta: 'Mariana Trench'},
           {domanda: 'Qual è il deserto più grande del mondo?', risposta: 'Sahara'},
            {domanda: 'Qual è il paese più popoloso dell\'europa?', risposta: 'Russia'},
             {domanda: 'Qual è il lago più grande del mondo?', risposta: 'Lago Superiore'},
              {domanda: 'Qual è il paese più piccolo del mondo in termini di superficie?', risposta: 'Città del Vaticano'},
               {domanda: 'Qual è la capitale del Giappone?', risposta: 'Tokyo'},
                {domanda: 'In quale stato degli Stati Uniti si trova il Grand Canyon?', risposta: 'Arizona'},
                 {domanda: 'Qual è la lingua più parlata al mondo?', risposta: 'Cinese mandarino'},
                  {domanda: 'In quale paese si trova l\'antica città di Machu Picchu?', risposta: 'Perù'},
                   {domanda: 'Qual è la catena montuosa più lunga del mondo?', risposta: 'Ande'},
                    {domanda: 'Qual è lo Stato più grande degli Stati Uniti?', risposta: 'Alaska'},
                     {domanda: 'Qual è la capitale dell\'italia?', risposta: 'Roma'},
                      {domanda: 'In quale oceano si trova l\'isola di Bali?', risposta: 'Oceano Indiano'},
                       {domanda: 'Qual è il paese più popoloso del mondo?', risposta: 'Cina'},
                        {domanda: 'Qual è il deserto più freddo del mondo?', risposta: 'Antartide'},
                         {domanda: 'Quale paese è situato sulle Alpi?', risposta: 'Svizzera'},
                          {domanda: 'Qual è il fiume principale di Parigi?', risposta: 'Senna'},
                           {domanda: 'Qual è la valle più grande del mondo?', risposta: 'Valle del Fiume Congo'},
                            {domanda: 'Qual è la capitale dell\'argentina?', risposta: 'Buenos Aires'},
                             {domanda: 'In quale continente si trova il Paese del Sudafrica?', risposta: 'Africa'},
                              {domanda: 'Qual è il lago più profondo del mondo?', risposta: 'Lago Baikal'},
                               {domanda: 'Qual è la capitale della Francia?', risposta: 'Parigi'},
                                {domanda: 'Qual è la montagna più famosa del Giappone?', risposta: 'Monte Fuji'},
                                 {domanda: 'In quale paese si trova la Grande Muraglia Cinese?', risposta: 'Cina'},
                                  {domanda: 'Qual è il punto più alto d\'europa?', risposta: 'Monte Elbrus'},
                                   {domanda: 'Qual è la città più popolosa dell\'india?', risposta: 'Mumbai'},
                                    {domanda: 'In quale Stato degli Stati Uniti si trova il Parco Nazionale dello Yellowstone?', risposta: 'Wyoming'},
                                     {domanda: 'Qual è la lingua ufficiale del Brasile?', risposta: 'Portoghese'},
                                      {domanda: 'Qual è il paese più piccolo del mondo in termini di popolazione?', risposta: 'Città del Vaticano'},
                                       {domanda: 'Qual è il fiume principale di Roma?', risposta: 'Tevere'},
                                        {domanda: 'Qual è la capitale dell\'india?', risposta: 'Nuova Delhi'},
                                         {domanda: 'Quale paese si trova tra la Francia e la Spagna?', risposta: 'Andorra'},
                                          {domanda: 'Quale oceano è situato ad est dell\'africa?', risposta: 'Oceano Indiano'},
                                           {domanda: 'Qual è il paese più grande dell\'oceania?', risposta: 'Australia'},
                                            {domanda: 'Qual è il termine scientifico per descrivere l\'ora zero del meridiano di Greenwich?', risposta: 'GMT (Greenwich Mean Time)'}

];