export const scienza = [
    {domanda: 'Quale è l\'elemento chimico più abbondante nel corpo umano?', risposta: 'Ossigeno'},
    {domanda: 'Quale fenomeno scientifico causa la formazione di un arcobaleno?', risposta: 'Rifrazione della luce'},
    {domanda: 'Quale è l\'unità di misura della temperatura?', risposta: 'Celsius'},
    {domanda: 'Quale è il pianeta più grande del sistema solare?', risposta: 'Giove'},
    {domanda: 'Cos\'è l\'evoluzione nelle scienze biologiche?', risposta: 'Processo di cambiamento e adattamento delle specie nel corso del tempo'},
    {domanda: 'Chi è considerato il padre della fisica moderna?', risposta: 'Isaac Newton'},
    {domanda: 'Qual è la velocità della luce nel vuoto?', risposta: '299792458 metri al secondo'},
    {domanda: 'Quale organo del corpo umano è responsabile della produzione di insulina?', risposta: 'Pancreas'},
    {domanda: 'Qual è l\'unità di misura della pressione atmosferica?', risposta: 'Pascal'},
    {domanda: "Chi scoprì l\'elettricità?", risposta: 'Benjamin Franklin'},
    {domanda: 'Cosa studia l\'astronomia?', risposta: 'Lo studio degli astri e dell\'universo'},
    {domanda: 'Qual è la formula chimica dell\'acqua?', risposta: 'H2O'},
    {domanda: 'Qual è l\'unità di misura dell\'energia?', risposta: 'Joule'},
    {domanda: 'Qual è il più piccolo osso del corpo umano?', risposta: 'Stirrup'},
    {domanda: 'Cosa misura il pH?', risposta: 'l\'acidità o basicità di una sostanza'},
    {domanda: 'Chi è stato il primo uomo a camminare sulla Luna?', risposta: 'Neil Armstrong'},
    {domanda: 'Quale pianeta del sistema solare è conosciuto come "pianeta rosso"?', risposta: 'Marte'},
    {domanda: 'Cos\'è la fotosintesi clorofilliana?', risposta: 'Il processo attraverso il quale le piante trasformano la luce solare in energia chimica'},
    {domanda: 'In qual\'anno è stata scoperta la radioattività?', risposta: '1896'},
    {domanda: 'Quale è l\'unità di misura della corrente elettrica?', risposta: 'Ampere'},
    {domanda: 'Chi è l\'autore della Teoria della Relatività?', risposta: 'Albert Einstein'},
    {domanda: 'Quale è l\'unità di misura della frequenza?', risposta: 'Hertz'},
    {domanda: 'Qual è il numero atomico dell\'ossigeno?', risposta: '8'},
    {domanda: 'Cosa studia la geologia?', risposta: 'Lo studio della Terra, delle sue rocce e dei processi che la modellano'},
    {domanda: 'Chi ha scoperto i raggi X?', risposta: 'Wilhelm Conrad Roentgen'},
    {domanda: 'Quanto è il valore approssimativo di π (pi greco)?', risposta: '3,14'},
    {domanda: 'Qual è l\'unità di misura della massa?', risposta: 'Chilogrammo'},
    {domanda: 'Quale è l\'unità di misura della lunghezza?', risposta: 'Metro'},
    {domanda: 'Chi ha formulato la teoria dell\'evoluzione per selezione naturale?', risposta: 'Charles Darwin'},
    {domanda: 'Quale è l\'unità di misura del tempo?', risposta: 'Secondo'},
    {domanda: 'Cos\'è la gravità?', risposta: 'Una forza di attrazione tra due oggetti con massa'},
    {domanda: 'Qual è l\'unità di misura dell\'angolo?', risposta: 'Radiante'},
    {domanda: 'Quale è l\'organo principale del sistema respiratorio?', risposta: 'Polmoni'},
    {domanda: 'Cosa studia la zoologia?', risposta: 'Lo studio degli animali'},
    {domanda: 'Quale è l\'unità di misura dell\'energia elettrica?', risposta: 'Wattora'},
    {domanda: 'Chi ha teorizzato la teoria dell\'evoluzione per selezione naturale insieme a Charles Darwin?', risposta: 'Alfred Russel Wallace'},
    {domanda: 'Quale è l\'organo principale del sistema nervoso?', risposta: 'Cervello'},
    {domanda: 'Cosa studia la botanica?', risposta: 'Lo studio delle piante'},
    {domanda: 'Qual è l\'unità di misura della potenza?', risposta: 'Watt'},
    {domanda: 'Chi ha scoperto la penicillina?', risposta: 'Alexander Fleming'},
    {domanda: 'Quale è l\'organo principale del sistema circolatorio?', risposta: 'Cuore'},
    {domanda: 'Cosa studia la fisica?', risposta: 'Le proprietà della materia e dell\'energia'},
    {domanda: 'Qual è l\'unità di misura della distanza?', risposta: 'Metro'},
    {domanda: 'Qual è l\'elemento più abbondante nell\'universo?', risposta: 'Idrogeno'},
    {domanda: 'Qual è l\'unità di misura della temperatura?', risposta: 'Grado Celsius'},
    {domanda: 'Qual è la forza di attrazione tra due corpi a causa della loro massa?', risposta: 'Forza di gravità'},
    {domanda: 'Qual è l\'organo principale nel sistema nervoso?', risposta: 'Cervello'},
    {domanda: 'Chi è accreditato per la scoperta della legge di gravità?', risposta: 'Isaac Newton'},
    {domanda: 'Qual è l\'unità di misura della pressione?', risposta: 'Pascal'},
    {domanda: 'Qual è la parte dell\'atomo che ha una carica positiva?', risposta: 'Il nucleo'},
    {domanda: 'Quale è la più grande specie di felino nel mondo?', risposta: 'Tigre siberiana'},
    {domanda: 'Chi ha inventato il primo telescopio?', risposta: 'Galileo Galilei'},
    {domanda: 'Qual è il processo di conversione della luce solare in energia chimica nelle piante?', risposta: 'Fotosintesi'},
    {domanda: 'Qual è la più piccola particella di un elemento chimico?', risposta: 'Atomo'},
    {domanda: 'Qual è l\'organo responsabile per la pulizia del sangue nel corpo umano?', risposta: 'Rene'},
    {domanda: 'Qual è il pianeta più vicino al sole?', risposta: 'Mercurio'},
    {domanda: 'In quale organo del corpo umano viene prodotta l\'insulina?', risposta: 'Pancreas'},
    {domanda: 'Qual è l\'unità di misura della lunghezza?', risposta: 'Metro'},
    {domanda: 'In quale stato si trova l\'acqua a una temperatura inferiore ai 0 gradi Celsius?', risposta: 'Stato solido (ghiaccio)'},
    {domanda: 'Qual è l\'organo principale nel sistema respiratorio?', risposta: 'Polmoni'},
    {domanda: 'Quale è l\'elemento chimico più abbondante nel corpo umano?', risposta: 'Ossigeno'},
    {domanda: 'Qual è l\'unità di misura della frequenza di un\'onda?', risposta: 'Hertz'},
    {domanda: 'Quale è l\'unità di misura della corrente elettrica?', risposta: 'Ampere'},
    {domanda: 'Qual è il principale componente dell\'aria?', risposta: 'Azoto'},
    {domanda: 'Quale gas rappresenta la maggior parte dell\'atmosfera terrestre?', risposta: 'Azoto'},
    {domanda: 'Quale è l\'organo responsabile per la conversione del cibo in energia?', risposta: 'Stomaco'},
    {domanda: 'Qual è la più grande struttura vivente sulla Terra?', risposta: 'La Grande Barriera Corallina'},
    {domanda: 'Quale è l\'organo responsabile per la regolazione della temperatura corporea?', risposta: 'Ipotalamo'},
    {domanda: 'Qual è l\'unità di misura della potenza elettrica?', risposta: 'Watt'},
    {domanda: 'Qual è il processo di trasformazione di un solido direttamente in gas senza passare per lo stato liquido?', risposta: 'Sublimazione'},
    {domanda: 'Qual è il metallo più leggero?', risposta: 'Litio'},
    {domanda: 'Quale è il processo attraverso il quale le piante convertono la luce solare in energia?', risposta: 'Fotosintesi'},
    {domanda: 'Quale è l\'unità di misura della capacità elettrica?', risposta: 'Farad'},
    {domanda: 'Quale elemento chimico è rappresentato dal simbolo Hg?', risposta: 'Mercurio'},
    {domanda: 'Quale è l\'organo responsabile per la produzione di bile nel corpo umano?', risposta: 'Fegato'},
    {domanda: 'Quali sono le tre fasi della materia?', risposta: 'Solido, liquido, gas'},
    {domanda: 'Qual è l\'unità di misura del lavoro?', risposta: 'Joule'},
    {domanda: 'Chi è stato il primo uomo a camminare sulla Luna?', risposta: 'Neil Armstrong'},
    {domanda: 'Qual è l\'unità di misura dell\'energia?', risposta: 'Joule'},
    {domanda: 'Quale è l\'organo primario nel sistema circolatorio?', risposta: 'Cuore'},
    {domanda: 'Qual è la più grande struttura dell\'universo?', risposta: 'Superammasso di galassie Laniakea'},
    {domanda: 'Qual è l\'elemento chimico con il numero atomico 1?', risposta: 'Idrogeno'},
    {domanda: 'Quale è l\'unità di misura della velocità?', risposta: 'Metri al secondo'},
];