export const serie = [
{domanda: 'Qual è il nome della famiglia protagonista de I Simpson?', risposta: 'Simpson'},
{domanda: 'Chi è l\'attore protagonista di Breaking Bad?', risposta: 'Bryan Cranston'},
{domanda: 'Quale serie televisiva parla delle avventure di un gruppo di amici nel loro bar preferito?', risposta: 'How I Met Your Mother'},
{domanda: 'Qual è il nome del protagonista di Sherlock Holmes nella serie TV "Sherlock"?', risposta: 'Benedict Cumberbatch'},
{domanda: 'Qual è il titolo della serie TV che racconta la storia di un gruppo di amici che vivono nella città di New York?', risposta: 'Friends'},
{domanda: 'Quale serie TV è ambientata nel Regno delle Due Sicilie?', risposta: 'Gomorra'},
{domanda: 'Qual è il nome del protagonista di The Big Bang Theory?', risposta: 'Sheldon Cooper'},
{domanda: 'Quale serie TV parla delle vicende di un gruppo di studenti al liceo?', risposta: 'Glee'},
{domanda: 'Qual è il titolo della serie TV ambientata nel mondo dei vampiri e dei licantropi?', risposta: 'True Blood'},
{domanda: 'Chi interpreta il personaggio di Tony Stark in Iron Man?', risposta: 'Robert Downey Jr.'},
{domanda: 'Quale serie TV parla delle avventure di un professore di chimica diventato produttore di metanfetamine?', risposta: 'Breaking Bad'},
{domanda: 'Qual è il nome del protagonista di House of Cards?', risposta: 'Frank Underwood'},
{domanda: 'Quale serie TV parla della vita di un gruppo di adolescenti nell\'upper East Side?', risposta: 'Gossip Girl'},
{domanda: 'Qual è il titolo della serie TV in cui i protagonisti devono sopravvivere a un\'apocalisse zombie?', risposta: 'The Walking Dead'},
{domanda: 'Chi è il personaggio principale della serie TV "Dexter"?', risposta: 'Dexter Morgan'},
{domanda: 'In quale serie TV è presente il personaggio di Rachel Green?', risposta: 'Friends'},
{domanda: 'Qual è il nome del protagonista maschile nella serie TV "Stranger Things"?', risposta: 'Mike Wheeler'},
{domanda: 'Quale serie televisiva parla della vita dei Medici durante il Rinascimento?', risposta: 'I Medici'},
{domanda: 'Qual è il nome del protagonista maschile nella serie TV "The Office"?', risposta: 'Michael Scott'},
{domanda: 'Chi è il personaggio principale della serie TV "Lost"?', risposta: 'Jack Shephard'},
{domanda: 'Quale serie TV parla delle vicende di una famiglia di avvocati?', risposta: 'The Good Wife'},
{domanda: 'Chi interpreta il personaggio di Walter White in Breaking Bad?', risposta: 'Bryan Cranston'},
{domanda: 'Quale serie TV parla delle avventure di un gruppo di supereroi?', risposta: 'The Avengers'},
{domanda: 'Qual è il titolo della serie TV in cui i protagonisti sono sopravvissuti a un volo aereo caduto su un\'isola?', risposta: 'Lost'},
{domanda: 'Chi è l\'attore protagonista di Grey\'s Anatomy?', risposta: 'Patrick Dempsey'},
{domanda: 'Quale serie TV parla della vita di un gruppo di contadini nell\'800?', risposta: 'l\'amica geniale'},
{domanda: 'Qual è il nome del protagonista di Game of Thrones?', risposta: 'Jon Snow'},
{domanda: 'Quale serie TV parla delle vicende di una famiglia mafiosa?', risposta: 'Il padrino'},
{domanda: 'Chi interpreta il personaggio di Tony Stark in Iron Man?', risposta: 'Robert Downey Jr.'},
{domanda: 'Quale serie TV parla delle avventure di un gruppo di amici nel loro bar preferito?', risposta: 'How I Met Your Mother'},
{domanda: 'Qual è il nome del protagonista di Sherlock Holmes nella serie TV "Sherlock"?', risposta: 'Benedict Cumberbatch'},
{domanda: 'Qual è il titolo della serie TV che racconta la storia di un gruppo di amici che vivono nella città di New York?', risposta: 'Friends'},
{domanda: 'Quale serie TV è ambientata nel Regno delle Due Sicilie?', risposta: 'Gomorra'},
{domanda: 'Qual è il nome del protagonista di The Big Bang Theory?', risposta: 'Sheldon Cooper'},
{domanda: 'Quale serie TV parla delle vicende di un gruppo di studenti al liceo?', risposta: 'Glee'},
{domanda: 'Qual è il titolo della serie TV ambientata nel mondo dei vampiri e dei licantropi?', risposta: 'True Blood'},
{domanda: 'Chi interpreta il personaggio di Tony Stark in Iron Man?', risposta: 'Robert Downey Jr.'},
{domanda: 'Quale serie TV parla delle avventure di un professore di chimica diventato produttore di metanfetamine?', risposta: 'Breaking Bad'},
{domanda: 'Qual è il nome del protagonista di House of Cards?', risposta: 'Frank Underwood'},
{domanda: 'Quale serie tv è ambientata a Westeros?', risposta: 'Game of Thrones'},
{domanda: 'Qual è il nome dello scienziato protagonista di "The Big Bang Theory"?', risposta: 'Sheldon Cooper'},
{domanda: 'In quale città è ambientata la serie "Friends"?', risposta: 'New York'},
{domanda: 'Chi interpreta il personaggio di Tony Stark in "Iron Man"?', risposta: 'Robert Downey Jr.'},
{domanda: 'Qual è il nome della protagonista di "La casa di carta"?', risposta: 'Tokyo'},
{domanda: 'In quale città sono ambientate le vicende di "Breaking Bad"?', risposta: 'Albuquerque'},
{domanda: 'Quale serie tv ha come protagonista un gruppo di scienziati che viaggiano nel tempo? ', risposta: 'Doctor Who'},
{domanda: 'Chi è l\'antagonista principale nella serie "Stranger Things"?', risposta: 'Il Demogorgone'},
{domanda: 'Qual è il nome della protagonista di "Grey\'s Anatomy"?', risposta: 'Meredith Grey'},
{domanda: 'In quale stato degli USA è ambientata la serie "The Walking Dead"?', risposta: 'Georgia'},
{domanda: 'Qual è il nome del protagonista in "Sherlock Holmes"?', risposta: 'Sherlock'},
{domanda: 'Chi interpreta il personaggio di Darth Vader in "Star Wars"?', risposta: 'David Prowse'},
{domanda: 'In quale città è ambientata la serie "The Crown"?', risposta: 'Londra'},
{domanda: 'Quale serie tv racconta le vicende di un gruppo di avvocati a New York City?', risposta: 'Suits'},
{domanda: 'Qual è il nome del protagonista di "The Office"?', risposta: 'Michael Scott'},
{domanda: 'In quale città è ambientata la serie tv "Peaky Blinders"?', risposta: 'Birmingham'},
{domanda: 'Quale serie tv ha come protagonista una famiglia di zombie?', risposta: 'The Walking Dead'},
{domanda: 'Chi interpreta il personaggio di Walter White in "Breaking Bad"?', risposta: 'Bryan Cranston'},
{domanda: 'Qual è il nome della protagonista di "Stranger Things"?', risposta: 'Eleven'},
{domanda: 'In quale città è ambientata la serie "How I Met Your Mother"?', risposta: 'New York'},
{domanda: 'Quale serie tv ha come protagonista un gruppo di sopravvissuti a un\'apocalisse nucleare?', risposta: 'The 100'},
{domanda: 'Chi è l\'antagonista principale nella serie "Game of Thrones"?', risposta: 'Cersei Lannister'},
{domanda: 'Qual è il nome del protagonista di "The Flash"?', risposta: 'Barry Allen'},
{domanda: 'In quale città è ambientata la serie "Sex and the City"?', risposta: 'New York'},
{domanda: 'Quale serie tv racconta le vicende di una famiglia mafiosa italo-americana?', risposta: 'The Sopranos'},
{domanda: 'Chi interpreta il personaggio di Jon Snow in "Game of Thrones"?', risposta: 'Kit Harington'},
{domanda: 'Qual è il nome del protagonista di "Dexter"?', risposta: 'Dexter Morgan'},
{domanda: 'In quale città è ambientata la serie tv "The Wire"?', risposta: 'Baltimore'},
{domanda: 'Quale serie tv ha come protagonista un gruppo di amici di Seattle che lavorano in un bar?', risposta: 'Cheers'},
{domanda: 'Chi è l\'antagonista principale nella serie "Dexter"?', risposta: 'Trinity Killer'},
{domanda: 'Qual è il nome del protagonista di "Breaking Bad"?', risposta: 'Walter White'},
{domanda: 'In quale città è ambientata la serie "The Office"?', risposta: 'Scranton'},
{domanda: 'Quale serie tv racconta le vicende di un gruppo di sopravvissuti a un\'epidemia zombie?', risposta: 'Fear the Walking Dead'},
{domanda: 'Chi interpreta il personaggio di Daenerys Targaryen in "Game of Thrones"?', risposta: 'Emilia Clarke'},
{domanda: 'Qual è il nome del protagonista di "Black Mirror"?', risposta: 'Non ha un protagonista fisso'},
{domanda: 'In quale città è ambientata la serie "Friends"?', risposta: 'New York'},
{domanda: 'Quale serie tv ha come protagonista un gruppo di amici che frequentano una scuola superiore?', risposta: 'Gossip Girl'},
{domanda: 'Chi è l\'antagonista principale nella serie "Stranger Things"?', risposta: 'Il Demogorgone'},
{domanda: 'Qual è il nome del protagonista di "The Walking Dead"?', risposta: 'Rick Grimes'},
{domanda: 'In quale città è ambientata la serie tv "The Big Bang Theory"?', risposta: 'Pasadena'},
]