/*

Scrivimi 10 domande di cultura generale sullo sport (non farle troppo difficili).  Scrivi la lista una di seguito all'altra separato da una virgola. Segui la seguente struttura {domanda: '<inserisci qui la domanda>', risposta: '<inserisci qui la risposta'},  {domanda: '<inserisci qui la domanda>', risposta: '<inserisci qui la risposta'}. 

*/

export const sport = [
    {domanda: 'Qual è il nome del famoso ciclista americano che ha vinto sette volte il Tour de France?', risposta: 'Lance Armstrong'},
    {domanda: 'In quale sport si effettua una mossa chiamata "smash"?', risposta: 'Tennis'},
    {domanda: 'Quale squadra di calcio italiana è conosciuta come "la Vecchia Signora"?', risposta: 'Juventus'},
    {domanda: 'Qual è il punto più alto in una partita di basket?', risposta: 'Schiacciata'},
    {domanda: 'In quale sport il termine "strike" è associato a un lancio perfetto?', risposta: 'Bowling'},
    {domanda: 'Chi è stato il primo uomo a correre la maratona in meno di due ore?', risposta: 'Eliud Kipchoge'},
    {domanda: 'Quale artista marziale è noto per la sua filosofia di "Jeet Kune Do" e il suo ruolo in "Enter the Dragon"?', risposta: 'Bruce Lee'},
    {domanda: 'Quale paese è considerato il luogo di nascita del rugby?', risposta: 'Inghilterra'},
    {domanda: 'In quale sport si usa una palla da cricket e uno "stump"?', risposta: 'Cricket'},
    {domanda: 'Quale squadra di calcio spagnola è famosa per i suoi colori blaugrana?', risposta: 'Barcelona (FC Barcelona o Barça)'},
    {domanda: 'Chi ha vinto l\'ultimo Campionato del Mondo di calcio?', risposta: 'Francia (nel 2018)'},
{domanda: 'Quale sport prevede una pista ovale e pattini a rotelle?', risposta: 'Il roller derby'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (1896)'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di tennis di Wimbledon?', risposta: 'La coppa del vincitore di Wimbledon'},
{domanda: 'Quale paese è famoso per la creazione del sumo?', risposta: 'Il Giappone'},
{domanda: 'Qual è il nome del torneo di golf più prestigioso al mondo?', risposta: 'Il Masters di Augusta'},
{domanda: 'In quale sport si usa una mazza per colpire una palla lanciata da un lanciatore?', risposta: 'Il baseball'},
{domanda: 'Chi è il pilota più giovane a vincere un campionato mondiale di Formula 1?', risposta: 'Sebastian Vettel'},
{domanda: 'Quale paese è noto per aver inventato il cricket?', risposta: 'L\'Inghilterra'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf Open Championship?', risposta: 'Claret Jug (brocca di argento)'},
{domanda: 'In quale sport si usa una pista, una bicicletta e una tuta aderente?', risposta: 'Il ciclismo su pista'},
{domanda: 'Chi è considerato il più grande giocatore di scacchi di tutti i tempi?', risposta: 'Garry Kasparov o Magnus Carlsen, a seconda delle opinioni'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf US Open?', risposta: 'Il trofeo dell\'US Open'},
{domanda: 'In quale sport si svolge la Ryder Cup?', risposta: 'Il golf'},
{domanda: 'Chi è considerato il "Re" del tennis su terra battuta?', risposta: 'Rafael Nadal'},
{domanda: 'Qual è il punteggio massimo possibile in una partita di biliardo?', risposta: '147'},
{domanda: 'Quale sport è conosciuto come "il re dei motori"?', risposta: 'La Formula 1'},
{domanda: 'Chi è stato il primo uomo a correre la maratona in meno di 2 ore?', risposta: 'Eliud Kipchoge (non ufficiale)'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di tennis degli US Open?', risposta: 'Coppa del vincitore degli US Open'},
{domanda: 'In quale sport si effettuano i tiri liberi?', risposta: 'Il basket'},
{domanda: 'Qual è il nome della squadra di calcio di Torino?', risposta: 'Torino FC'},
{domanda: 'In quale sport si utilizza un bastone per colpire una palla nel buco?', risposta: 'Il golf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona sotto le 2 ore?', risposta: 'Eliud Kipchoge (ufficialmente nel 2019)'},
{domanda: 'Qual è il nome del torneo di tennis più antico del mondo?', risposta: 'Il torneo di Wimbledon'},
{domanda: 'In quale sport si usa una rete e una palla per colpire in una zona contraria?', risposta: 'Il tennis'},
{domanda: 'Chi è considerato il "Fenomeno" nel calcio?', risposta: 'Ronaldo Nazário'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf del Masters di Augusta?', risposta: 'La giacca verde'},
{domanda: 'In quale sport si usa una pista ghiacciata e delle pietre?', risposta: 'Il curling'},
{domanda: 'Qual è il nome della squadra di calcio di Roma?', risposta: 'AS Roma'},
{domanda: 'In quale sport si utilizzano una tavola e delle vele per planare sull\'acqua?', risposta: 'Il windsurf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (1896)'},
{domanda: 'Quale sport prevede l\'uso di sci e fucile per colpire bersagli?', risposta: 'Il biathlon'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf The Open Championship?', risposta: 'Claret Jug'},
{domanda: 'In quale sport si effettuano i calci piazzati?', risposta: 'Il calcio'},
{domanda: 'Qual è il nome della squadra di calcio di Torino?', risposta: 'Torino FC'},
{domanda: 'Quale sport prevede il lancio di un disco metallico?', risposta: 'Il lancio del disco'},
{domanda: 'Chi è considerato il "Re" del tennis su erba?', risposta: 'Roger Federer'},
{domanda: 'In quale sport si usa una mazza per colpire una palla bianca in una buca?', risposta: 'Il golf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (nel 1896)'},
{domanda: 'Qual è il punteggio massimo possibile in una partita di bowling?', risposta: '300'},
]