/*

Scrivimi 10 domande di cultura generale sullo sport (non farle troppo difficili).  Scrivi la lista una di seguito all'altra separato da una virgola. Segui la seguente struttura {domanda: '<inserisci qui la domanda>', risposta: '<inserisci qui la risposta'},  {domanda: '<inserisci qui la domanda>', risposta: '<inserisci qui la risposta'}. 

*/

export const sport = [
    {domanda: 'Qual è il nome del famoso ciclista americano che ha vinto sette volte il Tour de France?', risposta: 'Lance Armstrong'},
    {domanda: 'In quale sport si effettua una mossa chiamata "smash"?', risposta: 'Tennis'},
    {domanda: 'Quale squadra di calcio italiana è conosciuta come "la Vecchia Signora"?', risposta: 'Juventus'},
    {domanda: 'Qual è il punto più alto in una partita di basket?', risposta: 'Schiacciata'},
    {domanda: 'In quale sport il termine "strike" è associato a un lancio perfetto?', risposta: 'Bowling'},
    {domanda: 'Chi è stato il primo uomo a correre la maratona in meno di due ore?', risposta: 'Eliud Kipchoge'},
    {domanda: 'Quale artista marziale è noto per la sua filosofia di "Jeet Kune Do" e il suo ruolo in "Enter the Dragon"?', risposta: 'Bruce Lee'},
    {domanda: 'Quale paese è considerato il luogo di nascita del rugby?', risposta: 'Inghilterra'},
    {domanda: 'In quale sport si usa una palla da cricket e uno "stump"?', risposta: 'Cricket'},
    {domanda: 'Quale squadra di calcio spagnola è famosa per i suoi colori blaugrana?', risposta: 'Barcelona (FC Barcelona o Barça)'},
    {domanda: 'Chi ha vinto l\'ultimo Campionato del Mondo di calcio?', risposta: 'Francia (nel 2018)'},
{domanda: 'Quale sport prevede una pista ovale e pattini a rotelle?', risposta: 'Il roller derby'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (1896)'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di tennis di Wimbledon?', risposta: 'La coppa del vincitore di Wimbledon'},
{domanda: 'Quale paese è famoso per la creazione del sumo?', risposta: 'Il Giappone'},
{domanda: 'Qual è il nome del torneo di golf più prestigioso al mondo?', risposta: 'Il Masters di Augusta'},
{domanda: 'In quale sport si usa una mazza per colpire una palla lanciata da un lanciatore?', risposta: 'Il baseball'},
{domanda: 'Chi è il pilota più giovane a vincere un campionato mondiale di Formula 1?', risposta: 'Sebastian Vettel'},
{domanda: 'Quale paese è noto per aver inventato il cricket?', risposta: 'L\'Inghilterra'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf Open Championship?', risposta: 'Claret Jug (brocca di argento)'},
{domanda: 'In quale sport si usa una pista, una bicicletta e una tuta aderente?', risposta: 'Il ciclismo su pista'},
{domanda: 'Chi è considerato il più grande giocatore di scacchi di tutti i tempi?', risposta: 'Garry Kasparov o Magnus Carlsen, a seconda delle opinioni'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf US Open?', risposta: 'Il trofeo dell\'US Open'},
{domanda: 'In quale sport si svolge la Ryder Cup?', risposta: 'Il golf'},
{domanda: 'Chi è considerato il "Re" del tennis su terra battuta?', risposta: 'Rafael Nadal'},
{domanda: 'Qual è il punteggio massimo possibile in una partita di biliardo?', risposta: '147'},
{domanda: 'Quale sport è conosciuto come "il re dei motori"?', risposta: 'La Formula 1'},
{domanda: 'Chi è stato il primo uomo a correre la maratona in meno di 2 ore?', risposta: 'Eliud Kipchoge (non ufficiale)'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di tennis degli US Open?', risposta: 'Coppa del vincitore degli US Open'},
{domanda: 'In quale sport si effettuano i tiri liberi?', risposta: 'Il basket'},
{domanda: 'Qual è il nome della squadra di calcio di Torino?', risposta: 'Torino FC'},
{domanda: 'In quale sport si utilizza un bastone per colpire una palla nel buco?', risposta: 'Il golf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona sotto le 2 ore?', risposta: 'Eliud Kipchoge (ufficialmente nel 2019)'},
{domanda: 'Qual è il nome del torneo di tennis più antico del mondo?', risposta: 'Il torneo di Wimbledon'},
{domanda: 'In quale sport si usa una rete e una palla per colpire in una zona contraria?', risposta: 'Il tennis'},
{domanda: 'Chi è considerato il "Fenomeno" nel calcio?', risposta: 'Ronaldo Nazário'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf del Masters di Augusta?', risposta: 'La giacca verde'},
{domanda: 'In quale sport si usa una pista ghiacciata e delle pietre?', risposta: 'Il curling'},
{domanda: 'Qual è il nome della squadra di calcio di Roma?', risposta: 'AS Roma'},
{domanda: 'In quale sport si utilizzano una tavola e delle vele per planare sull\'acqua?', risposta: 'Il windsurf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (1896)'},
{domanda: 'Quale sport prevede l\'uso di sci e fucile per colpire bersagli?', risposta: 'Il biathlon'},
{domanda: 'Qual è il nome del trofeo assegnato al vincitore del torneo di golf The Open Championship?', risposta: 'Claret Jug'},
{domanda: 'In quale sport si effettuano i calci piazzati?', risposta: 'Il calcio'},
{domanda: 'Qual è il nome della squadra di calcio di Torino?', risposta: 'Torino FC'},
{domanda: 'Quale sport prevede il lancio di un disco metallico?', risposta: 'Il lancio del disco'},
{domanda: 'Chi è considerato il "Re" del tennis su erba?', risposta: 'Roger Federer'},
{domanda: 'In quale sport si usa una mazza per colpire una palla bianca in una buca?', risposta: 'Il golf'},
{domanda: 'Chi è stato il primo uomo a correre una maratona alle Olimpiadi moderne?', risposta: 'Spyridon Louis (nel 1896)'},
{domanda: 'Qual è il punteggio massimo possibile in una partita di bowling?', risposta: '300'},
{domanda: 'Quale sport si gioca con una palla da tennis?', risposta: 'Tennis'},
{domanda: 'In quale città si trova il Colosseo?', risposta: 'Roma'},
{domanda: 'Qual è lo sport nazionale del Canada?', risposta: 'Hockey su ghiaccio'},
{domanda: 'Chi è considerato il più grande calciatore di tutti i tempi?', risposta: 'Pele'},
{domanda: 'Qual è la durata di un match di calcio?', risposta: '90 minuti'},
{domanda: 'Quale sport si pratica con una tavola e una vela?', risposta: 'Windsurf'},
{domanda: 'In quale paese sono nati gli sport olimpici?', risposta: 'Grecia'},
{domanda: 'Qual è lo sport di squadra più popolare al mondo?', risposta: 'Calcio'},
{domanda: 'Quale squadra di calcio italiana ha vinto più campionati?', risposta: 'Juventus'},
{domanda: 'Qual è il simbolo olimpico delle cinque cerchi intrecciate?', risposta: 'I cinque continenti'},
{domanda: 'Dove si svolgono i giochi olimpici invernali del 2022?', risposta: 'Pechino, Cina'},
{domanda: 'Chi ha vinto il campionato del mondo di Formula 1 nel 2020?', risposta: 'Lewis Hamilton'},
{domanda: 'Quale sport si pratica su un lungo tavolo con una pallina?', risposta: 'Tennis da tavolo'},
{domanda: 'Qual è lo sport invernale in cui si scivola su una discesa innevata?', risposta: 'Sci'},
{domanda: 'Chi è considerato il più grande giocatore di basket di tutti i tempi?', risposta: 'Michael Jordan'},
{domanda: 'Qual è il gioco da tavolo più popolare al mondo?', risposta: 'Scacchi'},
{domanda: 'In quale città si svolge il torneo di Wimbledon?', risposta: 'Londra'},
{domanda: 'Qual è lo sport in cui si tira una freccia verso un bersaglio?', risposta: 'Tiro con l\'arco'},
{domanda: 'Chi è stato il primo uomo a correre i 100 metri in meno di 10 secondi?', risposta: 'Donovan Bailey'},
{domanda: 'Da quanti giocatori è composta una squadra di pallamano?', risposta: 'Sette'},
{domanda: 'Qual è lo sport più praticato in Cina?', risposta: 'Ping pong'},
{domanda: 'Chi ha vinto il pallone d\'oro nel 2020?', risposta: 'Robert Lewandowski'},
{domanda: 'Qual è il simbolo della velocità nell\'atletica leggera?', risposta: 'Fiamma olimpica'},
{domanda: 'Qual è il giocatore di baseball con il più alto numero di fuoricampo?', risposta: 'Barry Bonds'},
{domanda: 'In quale anno si sono svolti i primi giochi olimpici moderni?', risposta: '1896'},
{domanda: 'Chi ha vinto il Super Bowl nel 2021?', risposta: 'Tampa Bay Buccaneers'},
{domanda: 'Quale sport si pratica nel pit di una pista automobilistica?', risposta: 'Formula 1'},
{domanda: 'Qual è il punto più alto del corpo umano?', risposta: 'Testa'},
{domanda: 'In quale sport si può segnare un touchdown?', risposta: 'Football americano'},
{domanda: 'Chi è stato il primo uomo a correre i 4 minuti nella mezza maratona?', risposta: 'Eliud Kipchoge'},
{domanda: 'Qual è il simbolo del rugby?', risposta: 'Ovolino'},
{domanda: 'Quale squadra di basket ha vinto più NBA Championships?', risposta: 'Boston Celtics'},
{domanda: 'In quale sport si usa una mazza per colpire una palla?', risposta: 'Baseball'},
{domanda: 'Chi è stato il primo uomo a camminare sulla luna?', risposta: 'Neil Armstrong'},
{domanda: 'Qual è il record mondiale nei 100 metri piani maschili?', risposta: '9,58 secondi'},
{domanda: 'Qual è lo sport di squadra più popolare negli Stati Uniti?', risposta: 'Football americano'},
{domanda: 'Quale sport si pratica con una tavola in cui si scivola su onde?', risposta: 'Surf'},
{domanda: 'Chi ha vinto il campionato europeo di calcio nel 2021?', risposta: 'Italia'},
{domanda: 'In quale sport si gioca nell\'Octagon?', risposta: 'MMA (Arti Marziali Miste)'},
{domanda: 'Qual è la dimensione standard di un campo da tennis?', risposta: '23,77 metri x 8,23 metri'},
{domanda: 'Chi ha vinto il premio FIFA World Player of the Year nel 2020?', risposta: 'Robert Lewandowski'},
]