export const storia = [
{domanda: 'In che anno ha inizio la Rivoluzione Francese?', risposta: '1789'},
{domanda: 'Chi è stato il primo presidente degli Stati Uniti d\'America?', risposta: 'George Washington'},
{domanda: 'Qual è l\'antica capitale dell\'Egitto?', risposta: 'Memphis'},
{domanda: 'Chi è stato il leader dell\'Unione Sovietica durante la Seconda Guerra Mondiale?', risposta: 'Josef Stalin'},
{domanda: 'In quale anno è stata firmata la Dichiarazione d\'Indipendenza degli Stati Uniti?', risposta: '1776'},
{domanda: 'Qual è stata la prima dinastia imperiale cinese?', risposta: 'La dinastia Qin'},
{domanda: 'Chi è stato il primo imperatore romano?', risposta: 'Augusto (o Ottaviano)'},
{domanda: 'In quale anno è stata la Caduta di Costantinopoli?', risposta: '1453'},
{domanda: 'Qual è stato il nome del programma spaziale statunitense che ha portato il primo uomo sulla Luna?', risposta: 'Apollo 11'},
{domanda: 'In quale anno è iniziata la Prima Guerra Mondiale?', risposta: '1914'},
{domanda: 'Chi fu il primo imperatore romano?', risposta: 'Augusto'},
{domanda: 'Qual è stata la causa principale della Rivoluzione Francese?', risposta: 'Disuguaglianza economica e sociale'},
{domanda: 'In quale anno è stata firmata la Dichiarazione d\'Indipendenza degli Stati Uniti?', risposta: '1776'},
{domanda: 'Chi è stato il fondatore dell\'Impero Mongolo?', risposta: 'Genghis Khan'},
{domanda: 'Quale evento storico è noto come "Il Grande Terrore"?', risposta: 'Il regno del terrore durante la Rivoluzione Francese'},
{domanda: 'Qual è stata la prima civiltà avanzata dell\'antico Egitto?', risposta: 'La civiltà dell\'Antico Regno'},
{domanda: 'Chi è stato il primo presidente degli Stati Uniti?', risposta: 'George Washington'},
{domanda: 'Qual è stata la causa principale della Guerra Civile Americana?', risposta: 'La schiavitù'},
{domanda: 'Qual è stato l\'evento che ha segnato l\'inizio della Prima Guerra Mondiale?', risposta: 'L\'assassinio dell\'Arciduca Francesco Ferdinando d\'Austria a Sarajevo'},
{domanda: 'Qual è stato il periodo noto come "Il Rinascimento"?', risposta: 'Dal XIV al XVII secolo'},
{domanda: 'Qual è stato il soggetto principale dei dipinti di Leonardo da Vinci?', risposta: 'Ritratti e temi religiosi'},
{domanda: 'Qual è stato il nome della nave su cui viaggiò Cristoforo Colombo nel 1492?', risposta: 'La Santa Maria'},
{domanda: 'In quale città è stata firmata la pace che ha posto fine alla Prima Guerra Mondiale?', risposta: 'Versailles'},
{domanda: 'Qual è stata la causa principale della Rivoluzione Industriale?', risposta: 'L\'innovazione tecnologica e l\'automazione'},
{domanda: 'Chi è stata la prima donna a volare da sola sull\'Atlantico?', risposta: 'Amelia Earhart'},
{domanda: 'Qual è stata la data dell\'attacco a Pearl Harbor?', risposta: '7 dicembre 1941'},
{domanda: 'In quale anno è stata fondata l\'Organizzazione delle Nazioni Unite (ONU)?', risposta: '1945'},
{domanda: 'Chi è stato il leader dell\'Unione Sovietica durante la Guerra Fredda?', risposta: 'Joseph Stalin'},
{domanda: 'Qual è stato il nome del primo uomo a camminare sulla Luna?', risposta: 'Neil Armstrong'},
{domanda: 'Qual è stata la data dell\'attentato alle Torri Gemelle di New York?', risposta: '11 settembre 2001'},
{domanda: 'Chi era il leader dell\'apartheid in Sudafrica?', risposta: 'Nelson Mandela'},
{domanda: 'Quale evento storico è noto come "La Rivoluzione d\'Ottobre"?', risposta: 'La presa del potere bolscevico in Russia nel 1917'},
{domanda: 'Qual è stata la causa principale della Guerra del Vietnam?', risposta: 'Coinvolgimento degli Stati Uniti nella Guerra Fredda e diffusione del comunismo'},
{domanda: 'In quale anno è caduto il Muro di Berlino?', risposta: '1989'},
{domanda: 'Qual è stato il nome del presidente degli Stati Uniti durante la Crisi dei Missili di Cuba?', risposta: 'John F. Kennedy'},
{domanda: 'Quale evento storico ha portato alla creazione dello stato d\'Israele nel 1948?', risposta: 'La Dichiarazione di Indipendenza d\'Israele'},
{domanda: 'In quale periodo storico è ambientato il famoso romanzo "Guerra e pace" di Tolstoj?', risposta: 'Durante le guerre napoleoniche'},
{domanda: 'Qual è stata la causa principale della Guerra delle Falkland/Malvinas tra Argentina e Regno Unito?', risposta: 'Disputa territoriale sulle isole Falkland/Malvinas'},
{domanda: 'Chi è stata la prima donna a essere eletta primo ministro del Regno Unito?', risposta: 'Margaret Thatcher'},
{domanda: 'Qual è stato il nome del presidente degli Stati Uniti durante la Guerra del Golfo?', risposta: 'George H. W. Bush'},
{domanda: 'Quale famoso discorso di Martin Luther King Jr. ha iniziato con le parole "I have a dream"?', risposta: 'Il discorso del 1963 a Washington D.C.'},
{domanda: 'In quale anno è stato istituito l\'Euro come moneta unica europea?', risposta: '1999'},
{domanda: 'Chi è stato il fondatore dell\'impero azteco?', risposta: 'Tenochtitlán'},
{domanda: 'Qual è stato il nome del comandante delle forze alleate durante la Seconda Guerra Mondiale?', risposta: 'Dwight D. Eisenhower'},
{domanda: 'In quale anno è caduto il regime comunista in Ungheria?', risposta: '1989'},
{domanda: 'Qual è stato il nome del primo presidente dell\'Africa del Sud post-apartheid?', risposta: 'Nelson Mandela'},
{domanda: 'Quale evento storico è noto come "La Marcia Selma-Montgomery"?', risposta: 'Una marcia per i diritti civili negli Stati Uniti nel 1965'},
{domanda: 'In quale anno è stata ratificata la Costituzione degli Stati Uniti?', risposta: '1787'},
{domanda: 'Chi è stato il fondatore dell\'impero romano?', risposta: 'Augusto'},
{domanda: 'Qual è stata la causa principale della Rivoluzione Russa del 1917?', risposta: 'Le condizioni sociali ed economiche precarie in Russia e l\'insoddisfazione della popolazione'},
{domanda: 'Qual è stata la dinastia più lunga nella storia della Cina?', risposta: 'La dinastia Zhou'},
{domanda: 'In quale anno è stata la caduta dell\'Impero Romano d\'Occidente?', risposta: '476 d.C.'},
{domanda: 'Chi è stato il leader dell\'Unione Sovietica dopo la morte di Stalin?', risposta: 'Nikita Khrushchev'},
{domanda: 'Qual è stato l\'evento che ha innescato la Guerra di Secessione americana?', risposta: 'L\'attacco a Fort Sumter nel 1861'},
{domanda: 'In quale anno è stato il terremoto di Lisbona, uno dei più distruttivi della storia?', risposta: '1755'},
{domanda: 'Chi è stato il comandante supremo delle forze alleate durante la Prima Guerra Mondiale?', risposta: 'Il generale Douglas Haig'},
{domanda: 'Qual è stato il nome della nave su cui viaggiò Cristoforo Colombo nel suo primo viaggio verso le Americhe?', risposta: 'La Santa Maria'},
{domanda: 'In quale anno è stata la firma della Magna Carta in Inghilterra?', risposta: '1215'},
{domanda: 'Qual è stata la dinastia regnante in Inghilterra durante il periodo della Rivoluzione Gloriosa?', risposta: 'La dinastia Stuart'},
{domanda: 'Chi è stato l\'autore del "Manifesto Comunista" insieme a Karl Marx?', risposta: 'Friedrich Engels'},
{domanda: 'Qual è stata la causa principale della Guerra Russo-Giapponese?', risposta: 'Disputa sulla Corea e sulla Manciuria'},
{domanda: 'In quale anno è stata la firma della Dichiarazione di Indipendenza dell\'India?', risposta: '1947'},
{domanda: 'Chi è stato il fondatore dell\'Impero Romano d\'Oriente, noto anche come Impero Bizantino?', risposta: 'Costantino il Grande'},
{domanda: 'Qual è stato l\'evento che ha innescato la Rivoluzione Russa del 1917?', risposta: 'La rivolta di febbraio e l\'abdicazione dello zar Nicola II'},
{domanda: 'In quale anno è stato il crollo dell\'Impero Ottomano?', risposta: '1922'},
{domanda: 'Chi è stato il leader della Rivoluzione Cubana nel 1959?', risposta: 'Fidel Castro'},
{domanda: 'Qual è stato il nome della nave su cui viaggiò Cristoforo Colombo nel suo secondo viaggio verso le Americhe?', risposta: 'La Maria'},
{domanda: 'In quale anno è stato il Trattato di Versailles che ha messo fine alla Prima Guerra Mondiale?', risposta: '1919'},
{domanda: 'Qual è stato il nome del faraone che ordinò la costruzione delle Grandi Piramidi di Giza?', risposta: 'Cheope'},
{domanda: 'Chi è stato il comandante delle forze alleate durante la Battaglia di Normandia nella Seconda Guerra Mondiale?', risposta: 'Il generale Dwight D. Eisenhower'},
{domanda: 'In quale anno è stata la caduta del Muro di Berlino?', risposta: '1989'},
{domanda: 'Qual è stato il nome del famoso esploratore cinese del XV secolo che viaggiò in Asia e in Africa?', risposta: 'Zheng He'},
{domanda: 'Chi è stato il leader dell\'apartheid in Sudafrica prima di diventare presidente?', risposta: 'Pieter Willem Botha'},
{domanda: 'Qual è stata la causa principale della Guerra di Cent\'Anni tra Inghilterra e Francia?', risposta: 'Dispute territoriali e di successione'},
{domanda: 'In quale anno è stata la fondazione di Roma secondo la leggenda romana?', risposta: '753 a.C.'},
{domanda: 'Chi è stato il leader del movimento per i diritti civili degli afroamericani negli Stati Uniti negli anni \'60?', risposta: 'Martin Luther King Jr.'},
{domanda: 'Qual è stato il nome della prima donna astronauta ad andare nello spazio?', risposta: 'Valentina Tereshkova'},
{domanda: 'In quale anno è stata la Rivoluzione Messicana?', risposta: '1910'},
{domanda: 'Chi è stato il fondatore dell\'Ordine dei Gesuiti?', risposta: 'Ignazio di Loyola'},
{domanda: 'Qual è stato il nome della nave su cui viaggiò Cristoforo Colombo nel suo terzo viaggio verso le Americhe?', risposta: 'La Santa Maria'},
{domanda: 'In quale anno è stata la firma del Trattato di Tordesillas tra Spagna e Portogallo?', risposta: '1494'},
{domanda: 'Chi è stato il generale dell\'Unione durante la Guerra Civile Americana?', risposta: 'Ulysses S. Grant'},
{domanda: 'Qual è stata la causa principale della Guerra dei Trent\'Anni in Europa?', risposta: 'Dispute religiose tra cattolici e protestanti'},
{domanda: 'In quale anno è stata la fondazione della città di New York?', risposta: '1626'},
{domanda: 'Chi è stata la prima donna a vincere un Premio Nobel?', risposta: 'Marie Curie'},
{domanda: 'Chi ha scritto l\'iliade?', risposta: 'Omero'},
{domanda: 'Qual è stata la capitale dell\'impero Romano?', risposta: 'Roma'},
{domanda: 'Chi ha scritto il trattato "Il Principe"?', risposta: 'Niccolò Machiavelli'},
{domanda: 'Quale fu l\'anno della scoperta dell\'america?', risposta: '1492'},
{domanda: 'Quale nazione ha lanciato il primo satellite nello spazio?', risposta: 'Unione Sovietica'},
{domanda: 'Chi è stato il primo presidente degli Stati Uniti?', risposta: 'George Washington'},
{domanda: 'Quali erano i nomi dei tre moschettieri?', risposta: 'Athos, Porthos, Aramis'},
{domanda: 'Chi era il re che ha firmato la Magna Carta?', risposta: 'Re Giovanni d\'Inghilterra'},
{domanda: 'Chi è stato il famoso compositore di musica classica austriaco?', risposta: 'Wolfgang Amadeus Mozart'},
{domanda: 'Quale è stata l\'antica città romana sepolta dall\'eruzione del Vesuvio?', risposta: 'Pompei'},
{domanda: 'In quale città si trova la Torre di Pisa?', risposta: 'Pisa'},
{domanda: 'Chi ha dipinto La Gioconda?', risposta: 'Leonardo da Vinci'},
{domanda: 'In quale anno si è conclusa la Seconda Guerra Mondiale?', risposta: '1945'},
{domanda: 'Chi è il pittore della Cappella Sistina?', risposta: 'Michelangelo'},
{domanda: 'Qual è stata la dinastia che ha governato la Cina per oltre 250 anni?', risposta: 'La dinastia Qing'},
{domanda: 'Quando è iniziata la Rivoluzione francese?', risposta: '1789'},
{domanda: 'Chi è stato l\'ultimo zar di Russia?', risposta: 'Nicola II'},
{domanda: 'Qual è stato il leader politico che ha guidato l\'india all\'indipendenza dal dominio britannico?', risposta: 'Mahatma Gandhi'},
{domanda: 'Quale è stata la prima dinastia imperiale cinese?', risposta: 'La dinastia Qin'},
{domanda: 'Quale fu la più grande civiltà precolombiana delle Americhe?', risposta: 'Gli Aztechi'},
{domanda: 'Chi fu il primo uomo a camminare sulla Luna?', risposta: 'Neil Armstrong'},
{domanda: 'In quale anno è stata dichiarata l\'indipendenza degli Stati Uniti?', risposta: '1776'},
{domanda: 'Qual è stato il paese che ha costruito la Grande Muraglia?', risposta: 'La Cina'},
{domanda: 'Chi è stato l\'ultimo faraone d\'Egitto?', risposta: 'Cleopatra'},
{domanda: 'Qual è stato l\'anno del colpo di stato chiamato "March on Rome"?', risposta: '1922'},
{domanda: 'In quale città si è svolta la Conferenza di Yalta?', risposta: 'Yalta'},
{domanda: 'Chi è stato il primo uomo a circumnavigare la Terra?', risposta: 'Ferdinand Magellan'},
{domanda: 'Qual è stata l\'età d\'oro dell\'impero Romano?', risposta: 'Il periodo dei Cinque Buoni Imperatori'},
{domanda: 'Chi ha scritto "1984" e "Animal Farm"?', risposta: 'George Orwell'},
{domanda: 'Qual è stata la prima capitale dell\'impero Romano?', risposta: 'Roma'},
{domanda: 'Qual è stata la guerra tra Atene e Sparta?', risposta: 'La guerra del Peloponneso'},
{domanda: 'Qual è stata la conquista di Genghis Khan?', risposta: 'l\'impero mongolo'},
{domanda: 'Chi è stato il fondatore dell\'islam?', risposta: 'Maometto'},
{domanda: 'In quale anno è iniziata la Prima Guerra Mondiale?', risposta: '1914'},
{domanda: 'Chi ha scritto "Don Chisciotte"?', risposta: 'Miguel de Cervantes'},
{domanda: "Qual è stata l\'antica civiltà che ha costruito le piramidi?", risposta: 'Gli antichi Egizi'},
{domanda: 'In quale città si trova il famoso Colosseo?', risposta: 'Roma'},
{domanda: 'Qual è stata la battaglia decisiva della Guerra di Troia?', risposta: 'La battaglia di Troia'},
{domanda: 'Chi ha scritto "Romeo e Giulietta"?', risposta: 'William Shakespeare'},
{domanda: 'Quale fu l\'anno della caduta dell\'impero Romano d\'Occidente?', risposta: '476 d.C.'},
{domanda: 'Chi è stato il filosofo greco che ha insegnato ad Alessandro Magno?', risposta: 'Aristotele'},
{domanda: 'In che anno è stata scoperta l\'america?', risposta: '1492'},
{domanda: 'Chi è stato il primo imperatore romano?', risposta: 'Augusto'},
{domanda: 'Quando è iniziata la prima guerra mondiale?', risposta: '1914'},
{domanda: 'Chi è stato il primo presidente degli Stati Uniti?', risposta: 'George Washington'},
{domanda: 'Qual è stato l\'ultimo impero della Storia?', risposta: 'l\'impero Ottomano'},
{domanda: 'Quando è stata fondata l\'Unione Europea?', risposta: '1957'},
{domanda: 'In quale città è stato firmato il trattato di pace che pose fine alla seconda guerra mondiale?', risposta: 'Potsdam'},
{domanda: 'Chi è stato il fondatore dell\'impero Mongolo?', risposta: 'Genghis Khan'},
{domanda: 'Quali sono state le due città atomiche giapponesi nella seconda guerra mondiale?', risposta: 'Hiroshima e Nagasaki'},
{domanda: 'Quali sono i tre stati del Benelux?', risposta: 'Belgio, Paesi Bassi, Lussemburgo'},
{domanda: 'Chi ha scritto "Il Principe"?', risposta: 'Niccolò Machiavelli'},
{domanda: 'In che anno è stata dichiarata l\'indipendenza degli Stati Uniti?', risposta: '1776'},
{domanda: 'Chi era il primo ministro britannico durante la seconda guerra mondiale?', risposta: 'Winston Churchill'},
{domanda: 'In che anno è iniziata la Rivoluzione Francese?', risposta: '1789'},
{domanda: 'Dove è stata firmata la Carta delle Nazioni Unite?', risposta: 'San Francisco'},
{domanda: 'In che anno è iniziata la Guerra Fredda?', risposta: '1947'},
{domanda: 'Chi è stato il primo uomo a camminare sulla Luna?', risposta: 'Neil Armstrong'},
{domanda: 'Quante colonie britanniche divennero gli Stati Uniti d\'America?', risposta: '13'},
{domanda: 'In che anno è iniziata la Guerra di Secessione negli Stati Uniti?', risposta: '1861'},
{domanda: 'Chi è stato il primo uomo a circumnavigare la Terra?', risposta: 'Ferdinand Magellan'},
{domanda: 'Qual è stato l\'impero più vasto della storia?', risposta: 'l\'impero Britannico'},
{domanda: 'Chi è stato il primo re d\'italia?', risposta: 'Vittorio Emanuele II'},
{domanda: 'Qual è stata la dinastia che ha governato l\'impero romano per più tempo?', risposta: 'La dinastia degli Antonini'},
{domanda: 'Dove è stata firmata la Dichiarazione d\'indipendenza degli Stati Uniti?', risposta: 'Filadelfia'},
{domanda: 'Chi ha dipinto la Gioconda?', risposta: 'Leonardo da Vinci'},
{domanda: 'Qual è stata la prima capitale dell\'impero Romano?', risposta: 'Roma'},
{domanda: 'In che anno è stata creata l\'olimpiade moderna?', risposta: '1896'},
{domanda: 'Chi ha scritto "La Divina Commedia"?', risposta: 'Dante Alighieri'},
{domanda: 'In che anno è stata costruita la Grande Muraglia Cinese?', risposta: '214 a.C.'},
{domanda: 'Qual è stato l\'ultimo zar di Russia?', risposta: 'Nicolò II'}
]